export const legacyRuTextByEn: Record<string, string> = {
  // Common
  'Back to inspection': 'Назад к проверке',
  'Back to inspections': 'Назад к проверкам',
  'Loading photo...': 'Загрузка фото...',
  'Photo not found': 'Фото не найдено',
  'Import a photo inside an inspection and open it from the photo gallery.':
    'Импортируй фото внутри проверки и открой его из галереи.',
  'Required': 'Обязательно',
  'REQUIRED': 'ОБЯЗАТЕЛЬНО',
  'Select value': 'Выбери значение',
  'Save form': 'Сохранить форму',
  'Saving...': 'Сохранение...',
  'Delete': 'Удалить',
  'Updated:': 'Обновлено:',
  'Created': 'Создано',
  'Updated': 'Обновлено',
  'Status': 'Статус',
  'Draft': 'Черновик',
  'Ready': 'Готово',
  'Exported': 'Экспортировано',
  'Success': 'Успешно',
  'No comment.': 'Комментария нет.',
  'Version': 'Версия',

  // Config Manager
  'Config Manager': 'Менеджер конфигов',
  'Load audit configurations from GitHub registry, local JSON files, or built-in demo files.':
    'Загрузка конфигов аудита из GitHub-реестра, локальных JSON-файлов или встроенных демо-файлов.',
  'GitHub registry': 'GitHub-реестр',
  'Load config registry index from GitHub and select one of the available audit configs.':
    'Загрузи индекс реестра конфигов из GitHub и выбери один из доступных конфигов аудита.',
  'Refresh': 'Обновить',
  'Registry URL': 'URL реестра',
  'GitHub registry loaded: 1 config(s) available.':
    'GitHub-реестр загружен: доступен 1 конфиг.',
  'Registry not loaded yet.': 'Реестр пока не загружен.',
  'Loading GitHub registry...': 'Загрузка GitHub-реестра...',
  'Local JSON': 'Локальный JSON',
  'Import a local config.json file and validate it with Zod before using it in the app.':
    'Импортируй локальный config.json и провалидируй его через Zod перед использованием в приложении.',
  'Upload config.json': 'Загрузить config.json',
  'Demo config': 'Демо-конфиг',
  'Load the built-in retail shelf audit demo config from public demo-configs.':
    'Загрузи встроенный демо-конфиг аудита полки из public demo-configs.',
  'Load demo config': 'Загрузить демо-конфиг',
  'Loading demo config...': 'Загрузка демо-конфига...',
  'Active config': 'Активный конфиг',
  'The active config is cached locally and will be restored after page reload.':
    'Активный конфиг кэшируется локально и будет восстановлен после перезагрузки страницы.',
  'Clear active config': 'Очистить активный конфиг',
  'No active config': 'Активный конфиг отсутствует',
  'Load a config from GitHub registry, demo config or local config.json file.':
    'Загрузи конфиг из GitHub-реестра, демо-конфиг или локальный config.json.',
  'Photo types': 'Типы фото',
  'Annotation types': 'Типы разметки',
  'Inspection fields': 'Поля проверки',
  'Photo fields': 'Поля фото',
  'Annotation fields': 'Поля разметки',
  'Dictionaries': 'Справочники',
  'Loaded at:': 'Загружено:',

  // Demo config labels
  'Retail Shelf Audit': 'Аудит полки',
  'Demo configuration for retail shelf photo audits, product areas, price tags and violations.':
    'Демо-конфигурация для фотоаудитов полки, товарных зон, ценников и нарушений.',
  'Overview': 'Обзор',
  'Price tag': 'Ценник',
  'Violation': 'Нарушение',
  'Product area': 'Товарная зона',
  'Competitor area': 'Зона конкурента',
  'Brand': 'Бренд',
  'Condition': 'Состояние',
  'Violation type': 'Тип нарушения',
  'Comment': 'Комментарий',
  'Store name': 'Название магазина',
  'Visit comment': 'Комментарий визита',
  'Photo comment': 'Комментарий к фото',

  // Export Center
  'Export Center': 'Центр экспорта',
  'Export, import, download and upload ZIP packages through storage adapters.':
    'Экспорт, импорт, скачивание и загрузка ZIP-пакетов через storage-адаптеры.',
  'Active config:': 'Активный конфиг:',
  'ZIP package pipeline': 'Пайплайн ZIP-пакета',
  'Import package': 'Импорт пакета',
  'Restore an exported ZIP package back into local IndexedDB. Re-importing the same package updates existing records by id.':
    'Восстановление экспортированного ZIP-пакета обратно в локальный IndexedDB. Повторный импорт того же пакета обновляет существующие записи по id.',
  'Import ZIP': 'Импорт ZIP',
  'Importing...': 'Импорт...',
  'AI suggestions import': 'Импорт AI-подсказок',
  'Import suggestions generated by n8n/backend AI pipeline. Suggestions are saved as annotations with source':
    'Импорт подсказок, сгенерированных n8n/backend AI-пайплайном. Подсказки сохраняются как аннотации с источником',
  'and can be reviewed in Annotator.': 'и могут быть проверены в разделе разметки.',
  'Generate & import demo': 'Сгенерировать и импортировать демо',
  'Download demo JSON': 'Скачать демо JSON',
  'Import AI suggestions': 'Импорт AI-подсказок',
  'Generating...': 'Генерация...',
  'Fast test: click': 'Быстрый тест: нажми',
  'Manual import requires real local': 'Ручной импорт требует реальные локальные',
  'and': 'и',
  'files with demo placeholders are rejected by design.':
    'файлы с demo placeholder отклоняются специально.',
  'Demo AI suggestions file generated:': 'Файл demo AI-подсказок создан:',
  'Now upload the downloaded JSON with': 'Теперь загрузи скачанный JSON через',
  'Demo AI suggestion generated and imported:': 'Demo AI-подсказка создана и импортирована:',
  'Open first affected photo': 'Открыть первое затронутое фото',
  'Storage adapter': 'Storage-адаптер',
  'Choose how to deliver generated ZIP packages: local download, HTTP endpoint or webhook.':
    'Выбери способ доставки созданных ZIP-пакетов: локальное скачивание, HTTP endpoint или webhook.',
  'Test adapter': 'Проверить адаптер',
  'Testing...': 'Проверка...',
  'Save adapter settings': 'Сохранить настройки адаптера',
  'Adapter': 'Адаптер',
  'Local download': 'Локальное скачивание',
  'Download the ZIP package directly in the browser.':
    'Скачать ZIP-пакет напрямую в браузере.',
  'Status:': 'Статус:',
  'configured': 'настроено',
  'not configured': 'не настроено',
  'Available inspections': 'Доступные проверки',
  'Download locally or upload through the configured storage adapter.':
    'Скачай локально или загрузи через настроенный storage-адаптер.',
  'Total:': 'Всего:',
  'Download ZIP': 'Скачать ZIP',
  'Exporting...': 'Экспорт...',
  'Uploading...': 'Загрузка...',
  'Preview manifest': 'Предпросмотр manifest',
  'Export jobs': 'Задачи экспорта',
  'Local downloads and uploads are tracked here. Failed jobs can be retried.':
    'Локальные скачивания и загрузки отслеживаются здесь. Ошибочные задачи можно повторить.',
  'Clear jobs': 'Очистить задачи',
  'No export jobs yet': 'Задач экспорта пока нет',
  'Download or upload a package to create the first export job.':
    'Скачай или загрузи пакет, чтобы создать первую задачу экспорта.',
  'Response': 'Ответ',
  'Retry': 'Повторить',
  'Open external job': 'Открыть внешнюю задачу',
  'attempts:': 'попыток:',
  'external job:': 'внешняя задача:',
  'transport:': 'транспорт:',

  // Photo annotator
  'Photo Annotator': 'Разметка фото',
  'Photo ID:': 'ID фото:',
  'Annotation panel': 'Панель разметки',
  'File': 'Файл',
  'Photo type': 'Тип фото',
  'Size': 'Размер',
  'New annotation type': 'Новый тип разметки',
  'Draw a rectangle on the photo. Created annotations are saved locally in IndexedDB. After creating or selecting an annotation, fill the dynamic form below.':
    'Нарисуй прямоугольник на фото. Созданные аннотации сохраняются локально в IndexedDB. После создания или выбора аннотации заполни динамическую форму ниже.',
  'Visible types': 'Видимые типы',
  'Source filter': 'Фильтр источника',
  'All': 'Все',
  'Human': 'Человек',
  'Imported': 'Импорт',
  'Pending AI': 'AI на проверке',
  'AI review': 'Проверка AI',
  'pending': 'на проверке',
  'AI suggestions are pending human review. Accept changes source to human. Reject deletes the suggestion.':
    'AI-подсказки ожидают проверки человеком. Accept меняет источник на human. Reject удаляет подсказку.',
  'Clear pending AI suggestions': 'Очистить AI-подсказки на проверке',
  'Annotations': 'Аннотации',
  'No annotations for the current filters.': 'Нет аннотаций для текущих фильтров.',
  'Dynamic form': 'Динамическая форма',
  'Select an annotation from the list or create a new one to fill the form.':
    'Выбери аннотацию из списка или создай новую, чтобы заполнить форму.',
  'Accept': 'Принять',
  'Reject': 'Отклонить',
  'AI metadata': 'AI-метаданные',
  'Form is not filled yet.': 'Форма пока не заполнена.',
  'selected': 'выбрано',
  'accepted AI': 'принято AI',
  'confidence:': 'уверенность:',

  // Annotator entry
  'Annotator': 'Разметка',
  'Select a photo from recent inspections and open the image annotation workspace.':
    'Выбери фото из последних проверок и открой рабочую область разметки.',
  'Recent photos': 'Последние фото',
  'Inspection groups': 'Группы проверок',
  'Entry point': 'Точка входа',
  'This page replaces the old demo photo route and prevents the confusing Photo not found state from the main navigation.':
    'Эта страница заменяет старый demo photo route и убирает непонятное состояние Photo not found из основной навигации.',
  'No photos yet': 'Фотографий пока нет',
  'Create an inspection, import photos, and return here to start annotation.':
    'Создай проверку, импортируй фотографии и вернись сюда для разметки.',
  'Open inspections': 'Открыть проверки',
  'Open annotator': 'Открыть разметку',
  'Open inspection': 'Открыть проверку',

  // Inspection detail
  'Checklist complete. Inspection is ready.': 'Чек-лист заполнен. Проверка готова.',
  'Checklist is not complete yet.': 'Чек-лист ещё не заполнен.',
  'Config': 'Конфиг',
  'Location': 'Локация',
  'Name': 'Название',
  'Address': 'Адрес',
  'Inspection checklist': 'Чек-лист проверки',
  'Form is built from config.inspectionForm and stored in inspection.attributes.':
    'Форма строится из config.inspectionForm и хранится в inspection.attributes.',
  'Save inspection checklist': 'Сохранить чек-лист проверки',
  'Photo gallery': 'Галерея фото',
  'Import one or more photos from gallery and fill photo-level checklist fields.':
    'Импортируй одно или несколько фото из галереи и заполни поля чек-листа уровня фото.',
  'Import photos': 'Импорт фото',
  'Import photos from gallery to start field photo annotation.':
    'Импортируй фото из галереи, чтобы начать полевую фоторазметку.',
  'No required fields': 'Нет обязательных полей',
  'Photo checklist': 'Чек-лист фото',
  'Save photo checklist': 'Сохранить чек-лист фото',
  'Annotate': 'Разметить',

  // Dynamic form
  'Yes / true': 'Да / true',
  'No options configured.': 'Опции не настроены.',
  'No dynamic form configured for the active config.':
    'Для активного конфига динамическая форма не настроена.'
};

export const legacyRuPatterns: Array<{
  pattern: RegExp;
  replacement: string;
}> = [
  {
    pattern: /^GitHub registry loaded: (\d+) config\(s\) available\.$/,
    replacement: 'GitHub-реестр загружен: доступно конфигов: $1.'
  },
  {
    pattern: /^Local registry fallback loaded: (\d+) config\(s\) available\.(.*)$/,
    replacement: 'Загружен локальный fallback-реестр: доступно конфигов: $1.$2'
  },
  {
    pattern: /^Active config restored: (.+)$/,
    replacement: 'Активный конфиг восстановлен: $1'
  },
  {
    pattern: /^Config loaded: (.+) v(.+)$/,
    replacement: 'Конфиг загружен: $1 v$2'
  },
  {
    pattern: /^Loading GitHub config: (.+)\.\.\.$/,
    replacement: 'Загрузка GitHub-конфига: $1...'
  },
  {
    pattern: /^Imported "(.+)" — (\d+) photos, (\d+) annotations\.$/,
    replacement: 'Импортировано "$1" — фото: $2, аннотаций: $3.'
  },
  {
    pattern: /^Local download started: "(.+)" — (\d+) photos, (\d+) annotations\.$/,
    replacement: 'Локальное скачивание запущено: "$1" — фото: $2, аннотаций: $3.'
  },
  {
    pattern: /^Upload completed: "(.+)" — (\d+) photos, (\d+) annotations\.(.*)$/,
    replacement: 'Загрузка завершена: "$1" — фото: $2, аннотаций: $3.$4'
  },
  {
    pattern: /^(\d+) photos$/,
    replacement: '$1 фото'
  },
  {
    pattern: /^(\d+) annotations$/,
    replacement: '$1 аннотаций'
  },
  {
    pattern: /^photos: \.\.\.$/,
    replacement: 'фото: ...'
  },
  {
    pattern: /^annotations: \.\.\.$/,
    replacement: 'аннотации: ...'
  },
  {
    pattern: /^Imported: (.+)$/,
    replacement: 'Импортировано: $1'
  },
  {
    pattern: /^Updated: (.+)$/,
    replacement: 'Обновлено: $1'
  },
  {
    pattern: /^Loaded at: (.+)$/,
    replacement: 'Загружено: $1'
  },
  {
    pattern: /^inspection: (.+)$/,
    replacement: 'проверка: $1'
  },
  {
    pattern: /^photo: (.+)$/,
    replacement: 'фото: $1'
  },
  {
    pattern: /^inspection title: (.+)$/,
    replacement: 'название проверки: $1'
  },
  {
    pattern: /^photo file: (.+)$/,
    replacement: 'файл фото: $1'
  },
  {
    pattern: /^Imported (\d+)\/(\d+) AI suggestions\.(.*)$/,
    replacement: 'Импортировано AI-подсказок: $1/$2.$3'
  },
  {
    pattern: /^Skipped duplicates: (\d+)\.$/,
    replacement: 'Пропущено дублей: $1.'
  },
  {
    pattern: /^confidence: (\d+)%$/,
    replacement: 'уверенность: $1%'
  }
];

export function translateLegacyUiTextToRu(value: string): string {
  const normalized = value.replace(/\s+/g, ' ').trim();

  if (!normalized) {
    return value;
  }

  const exact = legacyRuTextByEn[normalized];

  if (exact) {
    return value.replace(normalized, exact);
  }

  for (const item of legacyRuPatterns) {
    if (item.pattern.test(normalized)) {
      return value.replace(normalized, normalized.replace(item.pattern, item.replacement));
    }
  }

  return value;
}
