import { nanoid } from 'nanoid';

import type { AiSuggestionsPackage } from './aiSuggestionsImport';
import { importAiSuggestionsData } from './aiSuggestionsImport';
import { db } from '../db/db';
import { downloadBlob } from '../export/exportPackage';

export type GenerateDemoAiSuggestionsResult = {
  fileName: string;
  inspectionId: string;
  inspectionTitle: string;
  photoId: string;
  photoFileName: string;
  suggestionsCount: number;
};

export type GenerateAndImportDemoAiSuggestionsResult = GenerateDemoAiSuggestionsResult & {
  annotationsImported: number;
  skippedDuplicates: number;
  firstPhotoId?: string;
};

function sanitizeFileNamePart(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replaceAll('\\', '-')
      .replaceAll('/', '-')
      .replace(/[^a-z0-9а-яё._-]+/gi, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '') || 'item'
  );
}

function getDemoRectangle(input: {
  width?: number;
  height?: number;
}): {
  x: number;
  y: number;
  width: number;
  height: number;
} {
  const imageWidth = input.width && input.width > 0 ? input.width : 1200;
  const imageHeight = input.height && input.height > 0 ? input.height : 900;

  const rectWidth = Math.max(80, Math.round(imageWidth * 0.28));
  const rectHeight = Math.max(80, Math.round(imageHeight * 0.24));
  const x = Math.max(0, Math.round(imageWidth * 0.18));
  const y = Math.max(0, Math.round(imageHeight * 0.2));

  return {
    x,
    y,
    width: Math.min(rectWidth, imageWidth - x),
    height: Math.min(rectHeight, imageHeight - y),
  };
}

function buildRawAnnotoriousRectangle(input: {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
}): unknown {
  return {
    id: input.id,
    type: 'Annotation',
    target: {
      selector: {
        type: 'FragmentSelector',
        conformsTo: 'http://www.w3.org/TR/media-frags/',
        value: `xywh=pixel:${input.x},${input.y},${input.width},${input.height}`,
      },
    },
  };
}

async function buildDemoAiSuggestionsPackage(): Promise<{
  fileName: string;
  packageContent: AiSuggestionsPackage;
  result: GenerateDemoAiSuggestionsResult;
}> {
  const recentPhotos = await db.photos.orderBy('createdAt').reverse().limit(1).toArray();
  const photo = recentPhotos[0];

  if (!photo) {
    throw new Error('No photos found. Import at least one photo before generating AI suggestions.');
  }

  const inspection = await db.inspections.get(photo.inspectionId);

  if (!inspection) {
    throw new Error(`Inspection not found for photo: ${photo.id}`);
  }

  const suggestionId = `ai-demo-${nanoid()}`;
  const rectangle = getDemoRectangle({
    width: photo.width,
    height: photo.height,
  });

  const packageContent: AiSuggestionsPackage = {
    schemaVersion: '1.0.0',
    source: 'ai',
    provider: 'auditm-field-demo-generator',
    inspectionId: inspection.id,
    createdAt: new Date().toISOString(),
    suggestions: [
      {
        id: suggestionId,
        photoId: photo.id,
        type: 'product_area',
        label: 'Product area',
        shape: 'rectangle',
        confidence: 0.82,
        rawAnnotation: buildRawAnnotoriousRectangle({
          id: suggestionId,
          ...rectangle,
        }),
        attributes: {
          brand: 'Our brand',
          condition: 'OK',
          comment: 'Generated by local demo AI suggestions generator',
        },
        comment: 'Generated by local demo AI suggestions generator',
      },
    ],
    report: {
      summary: `Demo AI generator created one suggestion for photo "${photo.fileName}".`,
      warnings: [],
    },
  };

  const fileName = `ai-suggestions_${sanitizeFileNamePart(inspection.id)}_${sanitizeFileNamePart(
    photo.id,
  )}.json`;

  return {
    fileName,
    packageContent,
    result: {
      fileName,
      inspectionId: inspection.id,
      inspectionTitle: inspection.title,
      photoId: photo.id,
      photoFileName: photo.fileName,
      suggestionsCount: packageContent.suggestions.length,
    },
  };
}

export async function generateDemoAiSuggestionsFile(): Promise<GenerateDemoAiSuggestionsResult> {
  const { fileName, packageContent, result } = await buildDemoAiSuggestionsPackage();

  const blob = new Blob([JSON.stringify(packageContent, null, 2)], {
    type: 'application/json',
  });

  downloadBlob({
    blob,
    fileName,
  });

  return result;
}

export async function generateAndImportDemoAiSuggestions(): Promise<GenerateAndImportDemoAiSuggestionsResult> {
  const { result, packageContent } = await buildDemoAiSuggestionsPackage();
  const importResult = await importAiSuggestionsData(packageContent);

  return {
    ...result,
    annotationsImported: importResult.annotationsImported,
    skippedDuplicates: importResult.skippedDuplicates,
    firstPhotoId: importResult.firstPhotoId,
  };
}
