import { useState, type ChangeEvent } from 'react';
import { Link } from 'react-router';
import {
  AlertCircle,
  Bot,
  CheckCircle2,
  Download,
  ExternalLink,
  Sparkles,
  Upload,
  WandSparkles,
} from 'lucide-react';

import {
  importAiSuggestionsFile,
  type ImportAiSuggestionsResult,
} from '../../services/import/aiSuggestionsImport';
import {
  generateAndImportDemoAiSuggestions,
  generateDemoAiSuggestionsFile,
  type GenerateAndImportDemoAiSuggestionsResult,
  type GenerateDemoAiSuggestionsResult,
} from '../../services/import/aiSuggestionsMock';

export function AiSuggestionsImportPanel() {
  const [isImporting, setIsImporting] = useState(false);
  const [isGeneratingDemo, setIsGeneratingDemo] = useState(false);
  const [isGeneratingAndImportingDemo, setIsGeneratingAndImportingDemo] = useState(false);
  const [result, setResult] = useState<ImportAiSuggestionsResult | null>(null);
  const [demoResult, setDemoResult] = useState<GenerateDemoAiSuggestionsResult | null>(null);
  const [demoImportResult, setDemoImportResult] =
    useState<GenerateAndImportDemoAiSuggestionsResult | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const handleGenerateDemoSuggestions = async () => {
    try {
      setIsGeneratingDemo(true);
      setErrorMessage(null);
      setResult(null);
      setDemoResult(null);
      setDemoImportResult(null);

      const nextDemoResult = await generateDemoAiSuggestionsFile();

      setDemoResult(nextDemoResult);
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : 'Failed to generate demo AI suggestions.',
      );
    } finally {
      setIsGeneratingDemo(false);
    }
  };

  const handleGenerateAndImportDemoSuggestions = async () => {
    try {
      setIsGeneratingAndImportingDemo(true);
      setErrorMessage(null);
      setResult(null);
      setDemoResult(null);
      setDemoImportResult(null);

      const nextDemoImportResult = await generateAndImportDemoAiSuggestions();

      setDemoImportResult(nextDemoImportResult);
    } catch (error) {
      setErrorMessage(
        error instanceof Error
          ? error.message
          : 'Failed to generate and import demo AI suggestions.',
      );
    } finally {
      setIsGeneratingAndImportingDemo(false);
    }
  };

  const handleImportAiSuggestions = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];

    event.target.value = '';

    if (!file) {
      return;
    }

    try {
      setIsImporting(true);
      setErrorMessage(null);
      setResult(null);
      setDemoImportResult(null);

      const nextResult = await importAiSuggestionsFile(file);

      setResult(nextResult);
    } catch (error) {
      setErrorMessage(
        error instanceof Error ? error.message : 'Failed to import AI suggestions.',
      );
    } finally {
      setIsImporting(false);
    }
  };

  const firstAffectedPhotoId = result?.firstPhotoId ?? demoImportResult?.firstPhotoId;

  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex items-start gap-3">
          <div className="rounded-xl bg-slate-800 p-3">
            <Bot size={20} />
          </div>

          <div>
            <h2 className="text-xl font-semibold">AI suggestions import</h2>
            <p className="mt-1 text-sm leading-6 text-slate-400">
              Import suggestions generated by n8n/backend AI pipeline. Suggestions are saved as
              annotations with source <span className="font-mono text-slate-300">ai</span> and can
              be reviewed in Annotator.
            </p>
          </div>
        </div>

        <div className="flex flex-col gap-2 sm:flex-row">
          <button
            type="button"
            onClick={handleGenerateAndImportDemoSuggestions}
            disabled={isGeneratingAndImportingDemo}
            className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-100 px-4 py-3 text-sm font-medium text-slate-950 transition hover:bg-white disabled:cursor-not-allowed disabled:bg-slate-800 disabled:text-slate-500"
          >
            <WandSparkles size={16} />
            {isGeneratingAndImportingDemo ? 'Generating...' : 'Generate & import demo'}
          </button>

          <button
            type="button"
            onClick={handleGenerateDemoSuggestions}
            disabled={isGeneratingDemo}
            className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm font-medium text-slate-100 transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:border-slate-800 disabled:text-slate-600"
          >
            <Sparkles size={16} />
            {isGeneratingDemo ? 'Generating...' : 'Download demo JSON'}
          </button>

          <label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm font-medium text-slate-100 transition hover:bg-slate-800">
            <Upload size={16} />
            {isImporting ? 'Importing...' : 'Import AI suggestions'}
            <input
              type="file"
              accept=".json,application/json"
              className="hidden"
              disabled={isImporting}
              onChange={handleImportAiSuggestions}
            />
          </label>
        </div>
      </div>

      <div className="mt-4 rounded-xl border border-dashed border-slate-800 bg-slate-950 p-4 text-xs leading-5 text-slate-400">
        Fast test: click <span className="font-semibold text-slate-300">Generate & import demo</span>.
        Manual import requires real local <span className="font-mono text-slate-300">inspectionId</span>{' '}
        and <span className="font-mono text-slate-300">photoId</span>; files with demo placeholders
        are rejected by design.
      </div>

      {demoResult ? (
        <div className="mt-4 rounded-xl border border-sky-900 bg-sky-950/30 p-4 text-sm text-sky-100">
          <div className="flex items-center gap-3">
            <Download size={18} />
            <div>
              Demo AI suggestions file generated:{' '}
              <span className="font-mono">{demoResult.fileName}</span>
            </div>
          </div>

          <div className="mt-3 grid gap-2 text-xs text-sky-200/80 md:grid-cols-2">
            <div className="rounded-lg bg-sky-950 px-3 py-2">
              inspection: <span className="font-mono">{demoResult.inspectionId}</span>
            </div>
            <div className="rounded-lg bg-sky-950 px-3 py-2">
              photo: <span className="font-mono">{demoResult.photoId}</span>
            </div>
            <div className="rounded-lg bg-sky-950 px-3 py-2">
              inspection title: {demoResult.inspectionTitle}
            </div>
            <div className="rounded-lg bg-sky-950 px-3 py-2">
              photo file: {demoResult.photoFileName}
            </div>
          </div>

          <div className="mt-3 rounded-lg bg-sky-950 px-4 py-3 text-sky-100">
            Now upload the downloaded JSON with <span className="font-semibold">Import AI suggestions</span>.
          </div>
        </div>
      ) : null}

      {demoImportResult ? (
        <div className="mt-4 rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-sm text-emerald-100">
          <div className="flex items-center gap-3">
            <CheckCircle2 size={18} />
            <div>
              Demo AI suggestion generated and imported: {demoImportResult.annotationsImported}/
              {demoImportResult.suggestionsCount}.
              {demoImportResult.skippedDuplicates > 0
                ? ` Skipped duplicates: ${demoImportResult.skippedDuplicates}.`
                : ''}
            </div>
          </div>

          <div className="mt-3 grid gap-2 text-xs text-emerald-200/80 md:grid-cols-2">
            <div className="rounded-lg bg-emerald-950 px-3 py-2">
              inspection: <span className="font-mono">{demoImportResult.inspectionId}</span>
            </div>
            <div className="rounded-lg bg-emerald-950 px-3 py-2">
              photo: <span className="font-mono">{demoImportResult.photoId}</span>
            </div>
            <div className="rounded-lg bg-emerald-950 px-3 py-2">
              inspection title: {demoImportResult.inspectionTitle}
            </div>
            <div className="rounded-lg bg-emerald-950 px-3 py-2">
              photo file: {demoImportResult.photoFileName}
            </div>
          </div>
        </div>
      ) : null}

      {errorMessage ? (
        <div className="mt-4 flex items-center gap-3 rounded-xl border border-red-900 bg-red-950/40 px-4 py-3 text-sm text-red-100">
          <AlertCircle size={18} />
          {errorMessage}
        </div>
      ) : null}

      {result ? (
        <div className="mt-4 rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-sm text-emerald-100">
          <div className="flex items-center gap-3">
            <CheckCircle2 size={18} />
            <div>
              Imported {result.annotationsImported}/{result.suggestionsTotal} AI suggestions.
              {result.skippedDuplicates > 0 ? ` Skipped duplicates: ${result.skippedDuplicates}.` : ''}
            </div>
          </div>

          <div className="mt-3 flex flex-wrap gap-2 text-xs text-emerald-200/80">
            <span className="rounded-full bg-emerald-950 px-3 py-1">
              inspection: {result.inspectionId}
            </span>
            {result.provider ? (
              <span className="rounded-full bg-emerald-950 px-3 py-1">
                provider: {result.provider}
              </span>
            ) : null}
            <span className="rounded-full bg-emerald-950 px-3 py-1">
              photos: {result.affectedPhotoIds.length}
            </span>
          </div>

          {result.reportSummary ? (
            <div className="mt-3 rounded-lg bg-emerald-950 px-4 py-3 text-emerald-100">
              {result.reportSummary}
            </div>
          ) : null}

          {result.warnings.length > 0 ? (
            <div className="mt-3 rounded-lg border border-amber-900 bg-amber-950/40 px-4 py-3 text-amber-100">
              {result.warnings.join(' ')}
            </div>
          ) : null}
        </div>
      ) : null}

      {firstAffectedPhotoId ? (
        <Link
          to={`/photos/${firstAffectedPhotoId}/annotate`}
          className="mt-4 inline-flex items-center gap-2 rounded-xl bg-slate-100 px-4 py-3 text-sm font-medium text-slate-950 transition hover:bg-white"
        >
          Open first affected photo
          <ExternalLink size={14} />
        </Link>
      ) : null}
    </div>
  );
}
